#!/bin/sh

mkdir -p opk
cp ./tac08 opk/tac08
cp ./icon.png opk/icon.png
cp ./LICENSE opk/COPYING

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=tac08
Comment=Pico8 (Ported by gameblabla)
Exec=tac08 %f
Icon=icon
Terminal=false
Type=Application
Categories=emulators;
X-OD-NeedsDownscaling=true' > opk/default."$1".desktop

mksquashfs ./opk tac08_"$1".opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
